start_call:
  fields:
    to:
      required: true
      selector:
        text:

stop_call:
  fields:
    call_id:
      required: true
      selector:
        text:

send_sip_info_dtmf:
  fields:
    call_id:
      required: true
      selector:
        text:
    signal:
      required: true
      selector:
        text:
    duration:
      required: false
      selector:
        text:

get_active_calls:
  fields: {}
